
let quote = [`1. "Spread love everywhere you go. Let no one ever come to you without leaving happier." -Mother Teresa`, 
`2. "When you reach the end of your rope, tie a knot in it and hang on." -Franklin D. Roosevelt`, 
`3. "Always remember that you are absolutely unique. Just like everyone else." -Margaret Mead`, 
`4. "Don't judge each day by the harvest you reap but by the seeds that you plant." -Robert Louis Stevenson`, 
`5. "The future belongs to those who believe in the beauty of their dreams." -Eleanor Roosevelt`, 
`6. "Tell me and I forget. Teach me and I remember. Involve me and I learn." -Benjamin Franklin`, 
`7. "The best and most beautiful things in the world cannot be seen or even touched - they must be felt with the heart." -Helen Keller`, 
`8. "It is during our darkest moments that we must focus to see the light." -Aristotle`, 
`9. "Whoever is happy will make others happy too." -Anne Frank`, 
`10. "Do not go where the path may lead, go instead where there is no path and leave a trail." -Ralph Waldo Emerson`, 
`11. "If life were predictable it would cease to be life and be without flavor." -Eleanor Roosevelt`, 
`12. "In the end, it's not the years in your life that count. It's the life in your years." -Abraham Lincoln`, 
`13. "Life is a succession of lessons which must be lived to be understood." -Ralph Waldo Emerson`, 
`14. "You will face many defeats in life, but never let yourself be defeated." -Maya Angelou`, 
`15. "Never let the fear of striking out keep you from playing the game." -Babe Ruth`, 
`16. "Life is never fair, and perhaps it is a good thing for most of us that it is not." -Oscar Wilde`, 
`17. "The only impossible journey is the one you never begin." -Tony Robbins`, 
`18. "In this life we cannot do great things. We can only do small things with great love." -Mother Teresa`, 
`19. "Only a life lived for others is a life worthwhile." -Albert Einstein`, 
`20. "The purpose of our lives is to be happy." -Dalai Lama`, 
`21. "Life is what happens when you're busy making other plans." -John Lennon`, 
`22. "You only live once, but if you do it right, once is enough." -Mae West`, 
`23. "Live in the sunshine, swim the sea, drink the wild air." -Ralph Waldo Emerson`, 
`24. "Go confidently in the direction of your dreams! Live the life you've imagined." -Henry David Thoreau`, 
`25. "The greatest glory in living lies not in never falling, but in rising every time we fall." -Nelson Mandela`, 
`26. "Life is really simple, but we insist on making it complicated." -Confucius`, 
`27. "May you live all the days of your life." -Jonathan Swift`, 
`28. "Life itself is the most wonderful fairy tale." -Hans Christian Andersen`, 
`29. "Do not let making a living prevent you from making a life." -John Wooden`, 
`30. "Life is ours to be spent, not to be saved." -D. H. Lawrence`, 
`31. "Keep smiling, because life is a beautiful thing and there's so much to smile about." -Marilyn Monroe`, 
`32. "Life is a long lesson in humility." -James M. Barrie`, 
`33. "In three words I can sum up everything I've learned about life: it goes on." -Robert Frost`, 
`34. "Love the life you live. Live the life you love." -Bob Marley`, 
`35. "Life is either a daring adventure or nothing at all." -Helen Keller`, 
`36. "You have brains in your head. You have feet in your shoes. You can steer yourself any direction you choose." -Dr. Seuss`, 
`37. "Life is made of ever so many partings welded together." -Charles Dickens`, 
`38. "Your time is limited, so don't waste it living someone else's life. Don't be trapped by dogma — which is living with the results of other people's thinking." -Steve Jobs`, 
`39. "Life is trying things to see if they work." -Ray Bradbury`, 
`40. "Many of life's failures are people who did not realize how close they were to success when they gave up." -Thomas A. Edison`, 
`41. "The secret of success is to do the common thing uncommonly well." -John D. Rockefeller Jr.`, 
`42. "I find that the harder I work, the more luck I seem to have." -Thomas Jefferson`, 
`43. "Success is not final; failure is not fatal: It is the courage to continue that counts." -Winston S. Churchill`, 
`44. "The way to get started is to quit talking and begin doing." -Walt Disney`, 
`45. "Don't be distracted by criticism. Remember — the only taste of success some people get is to take a bite out of you." -Zig Ziglar`, 
`46. "Success usually comes to those who are too busy to be looking for it." -Henry David Thoreau`, 
`47. "I never dreamed about success, I worked for it." -Estee Lauder`, 
`48. "Success seems to be connected with action. Successful people keep moving. They make mistakes but they don't quit." -Conrad Hilton`, 
`49. "There are no secrets to success. It is the result of preparation, hard work, and learning from failure." -Colin Powell`, 
`50. "The real test is not whether you avoid this failure, because you won't. It's whether you let it harden or shame you into inaction, or whether you learn from it; whether you choose to persevere." -Barack Obama`, 
`51. "The only limit to our realization of tomorrow will be our doubts of today." -Franklin D. Roosevelt`, 
`52. "It is better to fail in originality than to succeed in imitation." -Herman Melville`, 
`53. "Successful people do what unsuccessful people are not willing to do. Don't wish it were easier; wish you were better." -Jim Rohn`, 
`54. "The road to success and the road to failure are almost exactly the same." -Colin R. Davis`, 
`55. "I failed my way to success." -Thomas Edison`, 
`56. "If you set your goals ridiculously high and it's a failure, you will fail above everyone else's success." -James Cameron`, 
`57. "If you really look closely, most overnight successes took a long time." -Steve Jobs`, 
`58. "A successful man is one who can lay a firm foundation with the bricks others have thrown at him." -David Brinkley`, 
`59. "Things work out best for those who make the best of how things work out." -John Wooden`, 
`60. "Try not to become a man of success. Rather become a man of value." -Albert Einstein`, 
`61. "Don't be afraid to give up the good to go for the great." -John D. Rockefeller`, 
`62. "Always bear in mind that your own resolution to success is more important than any other one thing." -Abraham Lincoln`, 
`63. "Success is walking from failure to failure with no loss of enthusiasm." -Winston Churchill`, 
`64. "You know you are on the road to success if you would do your job and not be paid for it." -Oprah Winfrey`, 
`65. "If you want to achieve excellence, you can get there today. As of this second, quit doing less-than-excellent work." -Thomas J. Watson`, 
`66. "If you genuinely want something, don't wait for it — teach yourself to be impatient." -Gurbaksh Chahal`, 
`67. "The only place where success comes before work is in the dictionary." -Vidal Sassoon`, 
`68. "If you are not willing to risk the usual, you will have to settle for the ordinary." -Jim Rohn`, 
`69. "Before anything else, preparation is the key to success." -Alexander Graham Bell`, 
`70. "People who succeed have momentum. The more they succeed, the more they want to succeed and the more they find a way to succeed. Similarly, when someone is failing, the tendency is to get on a downward spiral that can even become a self-fulfilling prophecy." -Tony Robbins`, 
`71. "Believe you can and you're halfway there." -Theodore Roosevelt`, 
`72. "The only person you are destined to become is the person you decide to be." -Ralph Waldo Emerson`, 
`73. "I've learned that people will forget what you said, people will forget what you did, but people will never forget how you made them feel." -Maya Angelou`, 
`74. "The question isn't who is going to let me; it's who is going to stop me." -Ayn Rand`, 
`75. "Winning isn't everything, but wanting to win is." -Vince Lombardi`, 
`76. "Whether you think you can or you think you can't, you're right." -Henry Ford`, 
`77. "You miss 100% of the shots you don't take." -Wayne Gretzky`, 
`78. "I alone cannot change the world, but I can cast a stone across the water to create many ripples." -Mother Teresa`, 
`79. "You become what you believe." -Oprah Winfrey`, 
`80. "The most difficult thing is the decision to act, the rest is merely tenacity." -Amelia Earhart`, 
`81. "How wonderful it is that nobody need wait a single moment before starting to improve the world." -Anne Frank`, 
`82. "An unexamined life is not worth living." -Socrates`, 
`83. "Everything you've ever wanted is on the other side of fear." -George Addair`, 
`84. "Dream big and dare to fail." -Norman Vaughan`, 
`85. "You may be disappointed if you fail, but you are doomed if you don't try." -Beverly Sills`, 
`86. "Life is 10% what happens to me and 90% of how I react to it." -Charles Swindoll`, 
`87. "Nothing is impossible, the word itself says, ‘I'm possible!'" -Audrey Hepburn`, 
`88. "It does not matter how slowly you go as long as you do not stop." -Confucius`, 
`89. "When everything seems to be going against you, remember that the airplane takes off against the wind, not with it." -Henry Ford`, 
`90. "Too many of us are not living our dreams because we are living our fears." -Les Brown`, 
`91. "I have learned over the years that when one's mind is made up, this diminishes fear." -Rosa Parks`, 
`92. "I didn't fail the test. I just found 100 ways to do it wrong." -Benjamin Franklin`, 
`93. "If you're offered a seat on a rocket ship, don't ask what seat! Just get on." -Sheryl Sandberg`, 
`94. "I attribute my success to this: I never gave or took any excuse." -Florence Nightingale`, 
`95. "I would rather die of passion than of boredom." -Vincent van Gogh`, 
`96. "If you look at what you have in life, you'll always have more. If you look at what you don't have in life, you'll never have enough." -Oprah Winfrey`, 
`97. "Dreaming, after all, is a form of planning." -Gloria Steinem`, 
`98. "Whatever the mind of man can conceive and believe, it can achieve." -Napoleon Hill`, 
`99. "First, have a definite, clear practical ideal; a goal, an objective. Second, have the necessary means to achieve your ends; wisdom, money, materials, and methods. Third, adjust all your means to that end." -Aristotle`, 
`100. "Twenty years from now you will be more disappointed by the things that you didn't do than by the ones you did do. So, throw off the bowlines, sail away from safe harbor, catch the trade winds in your sails. Explore, Dream, Discover." -Mark Twain`];

export default quote;